name: Node CI

# Push tests pushes; PR tests merges
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:

  # Test the build
  build:
    # Setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ ubuntu-latest ]

    # Go
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Env
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Git ref:    ${{ github.ref }}"
        echo "GH actor:   ${{ github.actor }}"
        echo "SHA:        ${{ github.sha }}"
        echo "OS ver:     ${{ runner.os }}"

    - name: Install
      run: npm install

    - name: Test
      run: npm test

    - name: Notify
      uses: sarisia/actions-status-discord@v1
      # Only fire alert once
      if: github.ref == 'refs/heads/main' && failure() && matrix.node-version == '14.x' && matrix.os == 'ubuntu-latest'
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "build and test"
        color: 0x222222
        username: GitHub Actions
